### ISSUE TITLE
Unexpected splitting of "boolean" type in conditional types

### ISSUE THREAD

**Issue by robbecoessens** [zjkipping/angular-typed-forms-helpers#1]
Problem is when you have a boolean formcontrol its gets spltted into `FormControl<false> | FormControl<true>` and not `FormControl<boolean>`

https://github.com/microsoft/TypeScript/issues/30280

For example: https://github.com/KostyaTretyak/ng-stack/commit/fbec6d84

Code example: https://stackblitz.com/edit/angular-typed-forms-helpers-demo-cdjrna?file=src%2Fapp%2Fapp.component.ts

**Comment by zjkipping** [comment]
This is an interesting edge case! Learned a thing about Booleans as well which is always great. I'll fix this real quick :)

**Comment by zjkipping** [comment]
@robbecoessens This should be resolved as of `3.1.3`!

**Comment by robbecoessens** [comment]
@zjkipping Wow, nice thanks for the quick fix ! :-)

**Comment by zjkipping** [comment]
@robbecoessens Thanks for the detailed issue :) Helped make it a quick fix.
