### ISSUE TITLE
Would it be possible to add support for Angular 17 ?

### ISSUE THREAD

**Issue by robbecoessens** [zjkipping/angular-typed-forms-helpers#3]

**Comment by zjkipping** [comment]
Can do! will publish another minor version, will report back with any extra info :)

**Comment by zjkipping** [comment]
@robbecoessens Angular v17.x.x should be supported by version 3.2.x that just got published! Let me know if you run into any issues, I only double checked that the example code we have still builds.

**Comment by robbecoessens** [comment]
I can confirm that it is working now for angular 17, thank you for the quick response and fix 🥇
