### ISSUE TITLE
Update Angular dependency to 18

### ISSUE THREAD

**Issue by NicolasMaas** [zjkipping/angular-typed-forms-helpers#6]
I wanted to make a small contribution but didn't know how 😅.

But could it be possible to update the Angular dependency?

**Comment by zjkipping** [comment]
Just a matter of updating the deps, I'll do this real quick since it takes a few seconds

**Comment by zjkipping** [comment]
Version `3.3.x` has released that supports angular v18.x.x. https://www.npmjs.com/package/@oasisdigital/angular-typed-forms-helpers
